// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FolderDialog() {
  return window['go']['main']['App']['FolderDialog']();
}

export function OpenDonationPage() {
  return window['go']['main']['App']['OpenDonationPage']();
}

export function RunUnpack(arg1, arg2) {
  return window['go']['main']['App']['RunUnpack'](arg1, arg2);
}

export function SetIncludeOverrides(arg1) {
  return window['go']['main']['App']['SetIncludeOverrides'](arg1);
}

export function ShowErrorDialog(arg1) {
  return window['go']['main']['App']['ShowErrorDialog'](arg1);
}

export function VerifyModpackFile(arg1) {
  return window['go']['main']['App']['VerifyModpackFile'](arg1);
}

export function ZipFileDialog() {
  return window['go']['main']['App']['ZipFileDialog']();
}
