// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FolderDialog():Promise<string>;

export function RunUnpack(arg1:string,arg2:string):Promise<boolean>;

export function ShowErrorDialog(arg1:string):Promise<void>;

export function VerifyModpackFile(arg1:string):Promise<string>;

export function ZipFileDialog():Promise<string>;
